# Generated by Django 2.2 on 2020-09-16 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
